### ISSUE TITLE
Create reports page

### ISSUE THREAD

**Issue by roji-tech** [tbf-challenge/teamwork-fe#33]
## Task Description

This task will be to design the UI for the admin view of the reports page and single report information page.

## Technical Considerations
1. Toggle between 'New', 'In Progress' and 'Completed' states
2. Disable different badge color for each type of report type
```css
.harrassment {
 background-color: var(--Error-Color-100);
 color: var(--Error-Color-700);
};

.abusive-behaviour{
 background-color: var(--Secondary-Color-100);
 color: var(--Secondary-Color-700);
};

.spasm{
 background-color: var(--Warning-Color-100);
 color: var(--Warning-Color-700);
};
```

## Additional ConsiderationsS

On click of the card of each report, navigate user to detailed report page.
Check globalStyles.js for all Color Variables
